export enum BahiaReconciliacionEstadoEnum {
  LIBRE = 'LIBRE',
  TRANSITO = 'TRANSITO',
  OCUPADO = 'OCUPADO',
  DISCREPANCIA = 'DISCREPANCIA',
  OFFLINE = 'OFFLINE',
  DESHABILITADO = 'DESHABILITADO',
}
