import { MigrationInterface, QueryRunner } from "typeorm";

export class StandardizeRelations1779367909070 implements MigrationInterface {
    name = 'StandardizeRelations1779367909070'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "codigo_otp" DROP CONSTRAINT "FK_otp_usuario"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "FK_usuario_tipo"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "FK_usuario_formacion"`);
        await queryRunner.query(`ALTER TABLE "bahia" DROP CONSTRAINT "FK_bahia_tipo"`);
        await queryRunner.query(`ALTER TABLE "bahia" DROP CONSTRAINT "FK_bahia_control"`);
        await queryRunner.query(`ALTER TABLE "movimiento_vehiculo" DROP CONSTRAINT "FK_movimiento_registro"`);
        await queryRunner.query(`ALTER TABLE "movimiento_vehiculo" DROP CONSTRAINT "FK_movimiento_bahia"`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" DROP CONSTRAINT "FK_registro_usuario"`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" DROP CONSTRAINT "FK_registro_vehiculo"`);
        await queryRunner.query(`ALTER TABLE "vehiculo" DROP CONSTRAINT "FK_vehiculo_tipo"`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" DROP CONSTRAINT "UQ_usuario_vehiculo"`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" DROP CONSTRAINT "UQ_usuario_vehiculo_sync"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "visitante_id_visitante_seq" OWNED BY "visitante"."id_visitante"`);
        await queryRunner.query(`ALTER TABLE "visitante" ALTER COLUMN "id_visitante" SET DEFAULT nextval('"visitante_id_visitante_seq"')`);
        await queryRunner.query(`ALTER TABLE "visitante" ALTER COLUMN "id_visitante" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "visitante" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "visitante" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "tipo_vehiculo_id_tipo_v_seq" OWNED BY "tipo_vehiculo"."id_tipo_v"`);
        await queryRunner.query(`ALTER TABLE "tipo_vehiculo" ALTER COLUMN "id_tipo_v" SET DEFAULT nextval('"tipo_vehiculo_id_tipo_v_seq"')`);
        await queryRunner.query(`ALTER TABLE "tipo_vehiculo" ALTER COLUMN "id_tipo_v" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "codigo_otp" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "codigo_otp" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "telemetria_evento_id_evento_seq" OWNED BY "telemetria_evento"."id_evento"`);
        await queryRunner.query(`ALTER TABLE "telemetria_evento" ALTER COLUMN "id_evento" SET DEFAULT nextval('"telemetria_evento_id_evento_seq"')`);
        await queryRunner.query(`ALTER TABLE "telemetria_evento" ALTER COLUMN "id_evento" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "telemetria_evento" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "telemetria_evento" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "sensor_id_sensor_seq" OWNED BY "sensor"."id_sensor"`);
        await queryRunner.query(`ALTER TABLE "sensor" ALTER COLUMN "id_sensor" SET DEFAULT nextval('"sensor_id_sensor_seq"')`);
        await queryRunner.query(`ALTER TABLE "sensor" ALTER COLUMN "id_sensor" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "alerta_sistema_id_alerta_seq" OWNED BY "alerta_sistema"."id_alerta"`);
        await queryRunner.query(`ALTER TABLE "alerta_sistema" ALTER COLUMN "id_alerta" SET DEFAULT nextval('"alerta_sistema_id_alerta_seq"')`);
        await queryRunner.query(`ALTER TABLE "alerta_sistema" ALTER COLUMN "id_alerta" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "alerta_sistema" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "alerta_sistema" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "contingencia_id_contingencia_seq" OWNED BY "contingencia"."id_contingencia"`);
        await queryRunner.query(`ALTER TABLE "contingencia" ALTER COLUMN "id_contingencia" SET DEFAULT nextval('"contingencia_id_contingencia_seq"')`);
        await queryRunner.query(`ALTER TABLE "contingencia" ALTER COLUMN "id_contingencia" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "contingencia" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "contingencia" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "auditoria_id_auditoria_seq" OWNED BY "auditoria"."id_auditoria"`);
        await queryRunner.query(`ALTER TABLE "auditoria" ALTER COLUMN "id_auditoria" SET DEFAULT nextval('"auditoria_id_auditoria_seq"')`);
        await queryRunner.query(`ALTER TABLE "auditoria" ALTER COLUMN "id_auditoria" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "auditoria" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "auditoria" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" ADD CONSTRAINT "UQ_68472e5fba85891f2bf65194a34" UNIQUE ("id_usuario", "id_vehiculo")`);
        await queryRunner.query(`ALTER TABLE "codigo_otp" ADD CONSTRAINT "FK_c7982857234f57262074b84d0fd" FOREIGN KEY ("usuario_documento") REFERENCES "usuario"("documento") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "FK_39fc0bf0d72443050f46bcadcf3" FOREIGN KEY ("tipo_usuario_id_tipo_usr") REFERENCES "tipo_usuario"("id_tipo_usr") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "FK_ffb9cd8da78ca239e9c85b7cabd" FOREIGN KEY ("formacion_ficha") REFERENCES "formacion"("ficha") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bahia" ADD CONSTRAINT "FK_2e24cdf58869055626b71770839" FOREIGN KEY ("tipo_bahia_id_tipo_b") REFERENCES "tipo_bahia"("id_tipo_b") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bahia" ADD CONSTRAINT "FK_67a6fa084924a6caa622eecf592" FOREIGN KEY ("tipo_control_id_tipo_c") REFERENCES "tipo_control"("id_tipo_c") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimiento_vehiculo" ADD CONSTRAINT "FK_9de16149bcef476860eac545336" FOREIGN KEY ("registro_vehiculo_id_registro_v") REFERENCES "registro_vehiculo"("id_registro_v") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimiento_vehiculo" ADD CONSTRAINT "FK_c215b3818ab28243c3afab91398" FOREIGN KEY ("bahia_id_bahia") REFERENCES "bahia"("id_bahia") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" ADD CONSTRAINT "FK_2a40626900ae93dd649f4a1cc6d" FOREIGN KEY ("usuario_documento") REFERENCES "usuario"("documento") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" ADD CONSTRAINT "FK_3970b48b1e91fa661c576eeaf48" FOREIGN KEY ("vehiculo_placa") REFERENCES "vehiculo"("placa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehiculo" ADD CONSTRAINT "FK_e04e38078099589c1f6d44be764" FOREIGN KEY ("tipo_vehiculo_id_tipo_v") REFERENCES "tipo_vehiculo"("id_tipo_v") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehiculo" DROP CONSTRAINT "FK_e04e38078099589c1f6d44be764"`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" DROP CONSTRAINT "FK_3970b48b1e91fa661c576eeaf48"`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" DROP CONSTRAINT "FK_2a40626900ae93dd649f4a1cc6d"`);
        await queryRunner.query(`ALTER TABLE "movimiento_vehiculo" DROP CONSTRAINT "FK_c215b3818ab28243c3afab91398"`);
        await queryRunner.query(`ALTER TABLE "movimiento_vehiculo" DROP CONSTRAINT "FK_9de16149bcef476860eac545336"`);
        await queryRunner.query(`ALTER TABLE "bahia" DROP CONSTRAINT "FK_67a6fa084924a6caa622eecf592"`);
        await queryRunner.query(`ALTER TABLE "bahia" DROP CONSTRAINT "FK_2e24cdf58869055626b71770839"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "FK_ffb9cd8da78ca239e9c85b7cabd"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "FK_39fc0bf0d72443050f46bcadcf3"`);
        await queryRunner.query(`ALTER TABLE "codigo_otp" DROP CONSTRAINT "FK_c7982857234f57262074b84d0fd"`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" DROP CONSTRAINT "UQ_68472e5fba85891f2bf65194a34"`);
        await queryRunner.query(`ALTER TABLE "auditoria" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "auditoria" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auditoria" ALTER COLUMN "id_auditoria" SET DEFAULT nextval('"auditoria_idAuditoria_seq"')`);
        await queryRunner.query(`ALTER TABLE "auditoria" ALTER COLUMN "id_auditoria" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "auditoria_id_auditoria_seq"`);
        await queryRunner.query(`ALTER TABLE "contingencia" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "contingencia" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "contingencia" ALTER COLUMN "id_contingencia" SET DEFAULT nextval('"contingencia_idContingencia_seq"')`);
        await queryRunner.query(`ALTER TABLE "contingencia" ALTER COLUMN "id_contingencia" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "contingencia_id_contingencia_seq"`);
        await queryRunner.query(`ALTER TABLE "alerta_sistema" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "alerta_sistema" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "alerta_sistema" ALTER COLUMN "id_alerta" SET DEFAULT nextval('"alerta_sistema_idAlerta_seq"')`);
        await queryRunner.query(`ALTER TABLE "alerta_sistema" ALTER COLUMN "id_alerta" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "alerta_sistema_id_alerta_seq"`);
        await queryRunner.query(`ALTER TABLE "sensor" ALTER COLUMN "id_sensor" SET DEFAULT nextval('"sensor_idSensor_seq"')`);
        await queryRunner.query(`ALTER TABLE "sensor" ALTER COLUMN "id_sensor" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "sensor_id_sensor_seq"`);
        await queryRunner.query(`ALTER TABLE "telemetria_evento" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "telemetria_evento" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "telemetria_evento" ALTER COLUMN "id_evento" SET DEFAULT nextval('"telemetria_evento_idEvento_seq"')`);
        await queryRunner.query(`ALTER TABLE "telemetria_evento" ALTER COLUMN "id_evento" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "telemetria_evento_id_evento_seq"`);
        await queryRunner.query(`ALTER TABLE "codigo_otp" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "codigo_otp" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tipo_vehiculo" ALTER COLUMN "id_tipo_v" SET DEFAULT nextval('tipo_vehiculo_idtipov_seq')`);
        await queryRunner.query(`ALTER TABLE "tipo_vehiculo" ALTER COLUMN "id_tipo_v" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "tipo_vehiculo_id_tipo_v_seq"`);
        await queryRunner.query(`ALTER TABLE "visitante" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "visitante" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "visitante" ALTER COLUMN "id_visitante" SET DEFAULT nextval('"visitante_idVisitante_seq"')`);
        await queryRunner.query(`ALTER TABLE "visitante" ALTER COLUMN "id_visitante" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "visitante_id_visitante_seq"`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" ADD CONSTRAINT "UQ_usuario_vehiculo_sync" UNIQUE ("id_usuario", "id_vehiculo")`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" ADD CONSTRAINT "UQ_usuario_vehiculo" UNIQUE ("id_usuario", "id_vehiculo")`);
        await queryRunner.query(`ALTER TABLE "vehiculo" ADD CONSTRAINT "FK_vehiculo_tipo" FOREIGN KEY ("id_tipo_vehiculo") REFERENCES "tipo_vehiculo"("id_tipo_v") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" ADD CONSTRAINT "FK_registro_vehiculo" FOREIGN KEY ("id_vehiculo") REFERENCES "vehiculo"("placa") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "registro_vehiculo" ADD CONSTRAINT "FK_registro_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("documento") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "movimiento_vehiculo" ADD CONSTRAINT "FK_movimiento_bahia" FOREIGN KEY ("id_bahia") REFERENCES "bahia"("id_bahia") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "movimiento_vehiculo" ADD CONSTRAINT "FK_movimiento_registro" FOREIGN KEY ("id_registro_vehiculo") REFERENCES "registro_vehiculo"("id_registro_v") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bahia" ADD CONSTRAINT "FK_bahia_control" FOREIGN KEY ("id_tipo_control") REFERENCES "tipo_control"("id_tipo_c") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bahia" ADD CONSTRAINT "FK_bahia_tipo" FOREIGN KEY ("id_tipo_bahia") REFERENCES "tipo_bahia"("id_tipo_b") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "FK_usuario_formacion" FOREIGN KEY ("id_formacion") REFERENCES "formacion"("ficha") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "FK_usuario_tipo" FOREIGN KEY ("id_tipo_usr") REFERENCES "tipo_usuario"("id_tipo_usr") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "codigo_otp" ADD CONSTRAINT "FK_otp_usuario" FOREIGN KEY ("documento") REFERENCES "usuario"("documento") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
